image: gitpod/workspace-full
tasks:
  - init: yarn install
    command: . ./setup.sh && npm run dev
ports:
  - port: 8888
    onOpen: open-browser
github:
  prebuilds:
    master: true
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: false
    addLabel: false
